version: '3'
services:
  gpt:
    build: ./gpt
    ports:
      - "50052:50052"
    networks:
      - my_network

  main:
    build: ./main
    ports:
      - "8000:8000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
