# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07service\"\x1d\n\nGPTRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\x0bGPTResponse\x12\r\n\x05reply\x18\x01 \x01(\t2H\n\nGPTService\x12:\n\x0bProcessData\x12\x13.service.GPTRequest\x1a\x14.service.GPTResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GPTREQUEST']._serialized_start=26
  _globals['_GPTREQUEST']._serialized_end=55
  _globals['_GPTRESPONSE']._serialized_start=57
  _globals['_GPTRESPONSE']._serialized_end=85
  _globals['_GPTSERVICE']._serialized_start=87
  _globals['_GPTSERVICE']._serialized_end=159
# @@protoc_insertion_point(module_scope)
